name: kotarica
description: Online buying and selling directly from people

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dio: ^3.0.10
  cupertino_icons: ^1.0.2
  web3dart: ^1.2.3
  web3dart2prerelease:
    path: ./web3dart-2.0.0-dev.9
  web_socket_channel: ^1.1.0
  http: ^0.12.2
  provider: ^5.0.0
  wallet_core: ^0.2.4+23
  font_awesome_flutter: ^9.0.0
  bubble_bottom_bar: ^1.2.0
  flutter_keychain: ^1.0.0 # flutter_secure_storage: ^4.1.0g
  dart_jsonwebtoken: ^1.1.0
  kf_drawer: ^1.1.2
  image_picker: ^0.6.7+7
  image_cropper: ^1.4.0
  shared_preferences: ^2.0.5
  shared_preferences_web: ^2.0.0
  intro_slider: ^2.3.4
  getwidget: ^1.1.0
  flutter_staggered_grid_view: ^0.3.4
  flappy_search_bar: ^1.4.1
  animated_icon_button: ^1.0.0
  multi_image_picker: ^4.8.0
  flutter_absolute_path: ^1.0.6
  clipboard: ^0.1.2+5
  ethereum_address: ^1.0.1
  date_format: ^2.0.2
  flutter_svg: ^0.21.0+1
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.6
  google_fonts: ^1.0.0
  flutter_vector_icons: ^1.0.0
  percent_indicator: ^3.0.1
  test: ^1.10.0
  mockito: ^4.1.1+1
  path_provider: ^2.0.1
  material_design_icons_flutter: ^3.2.3895
  flutter_local_notifications: ^4.0.1+2
  tuple: ^1.0.3
  carousel_slider: ^3.0.0
  full_screen_image: ^1.0.2
  intl: ^0.17.0
  badges: any
  image_picker_web_redux: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: BernHC
      fonts:
        - asset: fonts/BERNHC.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Medium.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: OpenSansItalic
      fonts:
        - asset: fonts/OpenSans-LightItalic.ttf



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - src/abis/
    - images/logo.png
    - images/send.png
    - images/profilePictureExample.jpg
    - images/welcome.png
    - images/empty_search.png
    - images/icons/back.png
    - images/icons/cart.png
    - images/icons/bag_1.png
    - images/icons/search.png
    - images/icons/heart.png
    - images/sir.jpg
    - images/sir2.png
    - images/icons/Trash.png
    - images/icons/add_to_cart.png
    - images/default.jpg
    - images/profilna.jpg
    - images/potkategorije/MlecniProizvodi/mleko.jpeg
    - images/potkategorije/MlecniProizvodi/jogurt.jpg
    - images/potkategorije/MlecniProizvodi/sir.jpg
    - images/potkategorije/MlecniProizvodi/kackavalj.jpg
    - images/potkategorije/MlecniProizvodi/Kajmak.jpg
    - images/potkategorije/MlecniProizvodi/kefir.jpg
    - images/potkategorije/MlecniProizvodi/kiselo_mleko.jpg
    - images/potkategorije/MlecniProizvodi/mlecni_namazi1.png
    - images/potkategorije/MlecniProizvodi/puter.jpg
    - images/potkategorije/MlecniProizvodi/surutka.jpg
    - images/potkategorije/MlecniProizvodi/ostalo.jpg
    - images/potkategorije/MlecniProizvodi/puter.jpg
    - images/potkategorije/suhomesnato/kobasica.jpg
    - images/potkategorije/suhomesnato/krava.jpg
    - images/potkategorije/suhomesnato/kulen.jpg
    - images/potkategorije/suhomesnato/mangulica.jpg
    - images/potkategorije/suhomesnato/prsuta.jpg
    - images/potkategorije/suhomesnato/slanina.jpg
    - images/potkategorije/suhomesnato/sunka.jpg
    - images/potkategorije/suhomesnato/ostalo.jpg
    - images/potkategorije/suhomesnato/ovca.jpg
    - images/potkategorije/SlaniSpajz/ajvar.jpg
    - images/potkategorije/SlaniSpajz/slaniNamazi.jpg
    - images/potkategorije/SlaniSpajz/sokoviPovrce.jpg
    - images/potkategorije/SlaniSpajz/sosovi.jpg
    - images/potkategorije/SlaniSpajz/tursija.jpg
    - images/potkategorije/slatkiSpajz/dzem.jpg
    - images/potkategorije/slatkiSpajz/kolaci.jpg
    - images/potkategorije/slatkiSpajz/slatkiNamaz.jpg
    - images/potkategorije/slatkiSpajz/torte.jpg
    - images/potkategorije/pica/beloVino.jpg
    - images/potkategorije/pica/vocniSokovi.jpg
    - images/potkategorije/pica/crvenoVino.jpg
    - images/potkategorije/pica/rakija.jpg
    - images/potkategorije/pica/crvenoVino.jpg
    - images/potkategorije/pica/vocnaVina.jpg
    - images/potkategorije/pica/roseVino.jpg
    - images/potkategorije/pica/sirup.jpg
    - images/potkategorije/mlin/brasno.jpg
    - images/potkategorije/mlin/testenine.jpg
    - images/potkategorije/med/med.jpg
    - images/potkategorije/med/proizvodiMed.jpg
    - images/potkategorije/vegan/cajevi.jpg
    - images/potkategorije/vegan/jabukovoSirce.jpg
    - images/potkategorije/vegan/maslinovoUlje.jpg
    - images/potkategorije/vegan/suncokretovoUlje.jpg
    - images/potkategorije/vegan/zacini.jpg
    - images/logoKotarica.png
    - images/potkategorije/voce/breskva.jpg
    - images/potkategorije/voce/dunja.jpg
    - images/potkategorije/voce/grozdje.jpg
    - images/potkategorije/voce/jabuka.jpg
    - images/potkategorije/voce/kajsija.jpg
    - images/potkategorije/voce/kruska.jpg
    - images/potkategorije/voce/sljiva.jpg
    - images/potkategorije/voce/tresnja.png
    - images/potkategorije/voce/visnja.jpg
    - images/potkategorije/povrce/boranija.jpg
    - images/potkategorije/povrce/grasak.jpg
    - images/potkategorije/povrce/karfiol.jpg
    - images/potkategorije/povrce/krastavac.jpg
    - images/potkategorije/povrce/krompir.jpg
    - images/potkategorije/povrce/kupus.jpg
    - images/potkategorije/povrce/lubenica.jpg
    - images/potkategorije/povrce/luk.jpg
    - images/potkategorije/povrce/paprika.jpg
    - images/potkategorije/povrce/paradajz.jpg
    - images/potkategorije/povrce/pasulj.jpg
    - images/potkategorije/povrce/sargarepa.jpg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
