/// Flutter icons Milk_subcategories
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Milk_subcategories
///      fonts:
///       - asset: fonts/Milk_subcategories.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Milk_subcategories {
  Milk_subcategories._();

  static const _kFontFam = 'Milk_subcategories';
  static const String _kFontPkg = null;

  static const IconData butter = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mozzarella = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sheep = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goat = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData butter_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cow__3_ = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
