// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationsApi.Database;

namespace NotificationsApi.Migrations
{
    [DbContext(typeof(NotificationsApiDbContext))]
    [Migration("20210521231730_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("NotificationsApi.Models.Chat", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Buyer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seller")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "Buyer", "Seller");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("NotificationsApi.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("messageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("productId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("receiverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("senderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NotificationsApi.Models.SeenNotification", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "TransactionHash", "LogIndex");

                    b.ToTable("SeenNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
